# Generated by Django 5.2.4 on 2025-07-12 15:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='algorithm',
            old_name='complexity',
            new_name='complexity_time',
        ),
        migrations.AddField(
            model_name='algorithm',
            name='algorithm_type',
            field=models.CharField(choices=[('sorting', 'Sorting'), ('searching', 'Searching'), ('pathfinding', 'Pathfinding')], default='sorting', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='algorithm',
            name='complexity_space',
            field=models.CharField(default='O(1)', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='algorithm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='algorithm',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='AlgorithmExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('array_size', models.IntegerField()),
                ('execution_time', models.FloatField()),
                ('comparisons', models.IntegerField(default=0)),
                ('swaps', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algorithm_api.algorithm')),
            ],
        ),
    ]
